### ISSUE TITLE
Datastore data stops working after a while

### ISSUE THREAD

**Issue by AquaRelliux** [jorgedlcruz/vmware-grafana#13]
Hello when I first import this the datastore data is visable but if I change the graph to display 5 minutes the data is N/A? Why is it going away after some time?

**Comment by jorgedlcruz** [comment]
Hello AquaRelliux, I guess the Datastore Capacity is checked every less often than 5 minutes, that is why, let me find the proper time of when the plugin does check the datastore, could be on VMware side even. Will let you know.

**Comment by AquaRelliux** [comment]
It continues not to show. For example today I need to go back a month for it to show data at all.  It can only gather data for the first second onces the dashboard is created. After that it is empty

**Comment by gokou340** [comment]
Can confirm, it works for a bit and then stops receiving data. Had to delete my influxDB and have it recreate it.

**Comment by jorgedlcruz** [comment]
Yes, you are right, I can see on my side that it does check every 10minutes, even more sometimes. Need to debug if this is vSphere behaviour or Telegraf, will beck and let you guys know

**Comment by AquaRelliux** [comment]
Even if you recreate the database it will stop after a while again. I don't know if it has to do with telegraf and how it collects data or the dashboard itself because I can see data in the database.

**Comment by jorgedlcruz** [comment]
I have uploaded a new Dashboard of the Overview, try that, it shouldn't fail after a while or anything, the dashboard will pick info from the DB, that's it, if you see data on your DB, and the Dashboard you select last 15 minutes and you have data within that time, it will render. Will probably need to find another way to show. Just to be clear, we are talking about the top chart on right, or the individual?

**Comment by AquaRelliux** [comment]
It is both the top and individual charts for me that mess up

**Comment by jorgedlcruz** [comment]
Cheers, it happens to me from time to time, it does change if I select more time like 30 mins or more, will need to see why we do not have more regular data, weird. Let me investigate

**Comment by jorgedlcruz** [comment]
Hello, please do try the latest Grafana v6.2, and download the latest version of the dashboard, I hope this fixes the issue, as it does make use of the new bar gauge panel

**Comment by AquaRelliux** [comment]
Nop still the same issue

Skickat från min iPhone

29 maj 2019 kl. 01:07 skrev Jorge de la Cruz <notifications@github.com<mailto:notifications@github.com>>:


Hello, please do try the latest Grafana v6.2, and download the latest version of the dashboard, I hope this fixes the issue, as it does make use of the new bar gauge panel

**Comment by jorgedlcruz** [comment]
Hello, a new Dashboard version has been uploaded, I think it does fix the issue, or at least it masquerade it by using the relative time, try it and let me know

**Comment by jorgedlcruz** [comment]
Adding the 3h relative time seems to have fixed the issue, feel free to reopen it if needed

**Comment by gokou340** [comment]
Still happening to me.

Updated to the latest Grafana, imported the latest dashboard. Everything was working, and then it just stopped and says "No Data" now.
