### ISSUE TITLE
VMware - vSphere Overview : panel y axis wrongly named for DT usage capacity

### ISSUE THREAD

**Issue by Venopsis** [jorgedlcruz/vmware-grafana#14]
Hello,

I noticed small issue about the overview dashboard. More precisely the panel "Datastores - Usage Capacity".

The data calculated is the used space and not the free space as mentioned on Y axis:

![image](https://user-images.githubusercontent.com/949573/57199302-b0d73600-6f7d-11e9-8153-da6c41e82ff4.png)

Adjusted label but good to know to fix by default on your side ;)

Good job for those impressive dashboard!

**Comment by jorgedlcruz** [comment]
Thank you so much! Fixed and closed!
