### ISSUE TITLE
VMware vSphere-VMs CPU Utilization Avg - no data points

### ISSUE THREAD

**Issue by pavel-pimenov** [jorgedlcruz/vmware-grafana#16]
Fix:
usage_average -> usagemhz_average
?

https://github.com/jorgedlcruz/vmware-grafana/blob/fbb5ef17326cbfb4f662bb690eee3d7b36a88be7/VMware%20vSphere%20%20-%20VMs.json#L518

https://github.com/influxdata/telegraf/blob/2566210df1e1ffba552b3379a09b443f3ddc3e3f/plugins/inputs/vsphere/vsphere.go#L76

**Comment by jorgedlcruz** [comment]
Hello, fixed on the last dashboard you can find on the repo and on grafana.com dashboards
