### ISSUE TITLE
vSphere overview - blank

### ISSUE THREAD

**Issue by Biomains** [jorgedlcruz/vmware-grafana#17]
Just installed telegraf and imported your grafana dashboards. The only dashboard that works, is the one for HOSTS. Overview, VM and Datastore are blank.
Anyone have any insight to what could be wrong?

**Comment by Biomains** [comment]
After reading some of the closed issues, I upgraded Grafana to newest version, and it look much better. 
Except the VM's boards. We have over 700 VM's. It's not loading, the browser hangs.

**Comment by jorgedlcruz** [comment]
Hello, thanks for the feedback, the load of the VMs should be better using the latest Grafana, as it does use a lazy load for it.

Also, I do remember the VMs where minimized so it should be just the rows loading, can you please attach a screenshot of how the VMs looks like?

**Comment by Biomains** [comment]
It loaded eventually. Very slow. But OK , it works. Thanks!

**Comment by jorgedlcruz** [comment]
Will close it then :) And try to get a 700VM environment to see how I can improve it
