### ISSUE TITLE
VMware vSphere -VMs - show only 10VMs

### ISSUE THREAD

**Issue by tmihaldinec** [jorgedlcruz/vmware-grafana#18]
Hi,
i have more than 300+ VMs and in VM dashboard i can only see 10 random VMs

is there any way to increase number of showed VMs/page
thanks
tomislav

**Comment by jorgedlcruz** [comment]
Hello,
This should not be the case, please download the new VM Dashboard and let me know

**Comment by jorgedlcruz** [comment]
Non answer for a long time, closing it now
