### ISSUE TITLE
Metric Mappings are wrong for some Panels Hosts/vms

### ISSUE THREAD

**Issue by madmax01** [jorgedlcruz/vmware-grafana#19]
Total Disk Latency = it shows "KBps" but should be ms

Storage Adapter Latency = should be deviceReadLatency_average and deviceWriteLatency_average (but it shows numberReadAveraged_average and numberWriteAveraged_average). So instead of Latency it shows the Commands Issues per Second

it would be nice to see how to implement as well kernel latency and guest latency and other kind of Panels if needed.

**Comment by jorgedlcruz** [comment]
Hello madmax01,
Appreciated a lot the feedback, new version can be found on the repo and on grafana.com Dashboards, THANK YOU!
