### ISSUE TITLE
VMware vSphere Overview - Datastore Overview broken when datastore has dots in name

### ISSUE THREAD

**Issue by tojaskiba** [jorgedlcruz/vmware-grafana#2]
VMware vSphere Overview - Datastore Overview broken when datastore has dots in name
![grafana vmware vsphere overview](https://user-images.githubusercontent.com/6915534/46399833-2c77b880-c6f9-11e8-95a0-384a6eee9045.png)
error is error parsing query: found ., expected regex at line 1, char 117

Proposed fix, pull requested

**Comment by tojaskiba** [comment]
#3

**Comment by jorgedlcruz** [comment]
Thank you, already merged and uploaded to https://grafana.com/api/dashboards/8159/revisions/10/download as well
