### ISSUE TITLE
Alerts

### ISSUE THREAD

**Issue by madmax01** [jorgedlcruz/vmware-grafana#20]
Hows possible to generate Alerts for Special Tresholds?

**Comment by jorgedlcruz** [comment]
Hello madmax01, you can generate alerts, yes, more information here - https://jorgedelacruz.uk/2019/09/27/grafana-using-microsoft-teams-for-our-notifications-when-established-thresholds-are-exceeded/ Let me know, you can always use Kapacitor if you need as well
