### ISSUE TITLE
VMware vSphere -VMs - show only 20VMs

### ISSUE THREAD

**Issue by lxjmac** [jorgedlcruz/vmware-grafana#21]
Hi,
i have more than 300+ VMs and in VM dashboard i can only see 20 random VMs

is there any way to increase number of showed VMs/page
thanks

My System Version
telegraf-1.13.1-1.x86_64
influxdb-1.7.9-1.x86_64
grafana-6.5.3-1.x86_64

![1](https://user-images.githubusercontent.com/50618576/72677220-02f0c500-3ad5-11ea-90b5-500b93d64180.png)
![2](https://user-images.githubusercontent.com/50618576/72677221-03895b80-3ad5-11ea-8c40-00e698037615.png)

**Comment by jorgedlcruz** [comment]
Hello,
The configuration needs to be tweaked like this:
```
[[inputs.vsphere]]
  interval = "60s"
  vcenters = [ "https://someaddress/sdk" ]
  username = "someuser@vsphere.local"
  password = "secret"

  vm_metric_include = []
  host_metric_include = []
  datastore_metric_exclude = ["*"]

  max_query_metrics = 256
  timeout = "60s"
  insecure_skip_verify = true

[[inputs.vsphere]]
interval = "300s"
  vcenters = [ "https://someaddress/sdk" ]
  username = "someuser@vsphere.local"
  password = "secret"

  datastore_metric_include = [ "disk.capacity.latest", "disk.used.latest", "disk.provisioned.latest" ]
  cluster_metric_include = []
  datacenter_metric_include = [] 
  insecure_skip_verify = true
  force_discover_on_init = true
  host_metric_exclude = ["*"] # Exclude realtime metrics
  vm_metric_exclude = ["*"] # Exclude realtime metrics

  max_query_metrics = 256
  collect_concurrency = 3
```
I have that and I can see my 61 VMs

**Comment by jorgedlcruz** [comment]
Did this change help at all?

**Comment by jorgedlcruz** [comment]
Non answer for a long time, closing it now
