### ISSUE TITLE
vmware-vsphere-overview: VM Disk Performance values issue

### ISSUE THREAD

**Issue by BunnyRush-LMA** [jorgedlcruz/vmware-grafana#22]
Hi, 
the module shows completely different values when choosing different time ranges. For example, in seven days at VM peak value = 1,053K iops, if you take in three days = 3,049K iops, if you select this peak value (cut in 5 hours) = 12,56K iops, in 30 minutes = 15,76K iops

![image](https://user-images.githubusercontent.com/22468355/75026823-a48d7c80-54ae-11ea-8067-b38301216b91.png)

![image](https://user-images.githubusercontent.com/22468355/75027932-6c873900-54b0-11ea-8ccc-1080308d0fab.png)

![image](https://user-images.githubusercontent.com/22468355/75027964-77da6480-54b0-11ea-820f-ebdd3680bcfb.png)

![image](https://user-images.githubusercontent.com/22468355/75027979-7e68dc00-54b0-11ea-9ede-5a634e73b449.png)

**Comment by jorgedlcruz** [comment]
Hello, can you try the latest version of the dashboards? Closing it, for now, let me know
