### ISSUE TITLE
vSphere - Hosts cpu usage

### ISSUE THREAD

**Issue by lasse-kristensen** [jorgedlcruz/vmware-grafana#23]
I use your VMware Vsphere - Hosts grafana dashboard, but when I looked at the CPU Usage, it didn't reflect what i was seeing in the vSphere client.
I found that the query didn't use the instance-total cpu WHERE clause
After adding this it reflected what I saw i vSphere.

`SELECT mean("usage_average") FROM "vsphere_host_cpu" WHERE ("esxhostname" =~ /^$esxi$/ AND "cpu" = 'instance-total') AND $timeFilter GROUP BY time($__interval) fill(null)`

Thanks a lot for creating great dashboards.

**Comment by The-Funk** [comment]
Hi there! Where did you make this change? I'm noticing an issue with the dashboard reporting 100% CPU usage and similar RAM usage.

**Comment by jorgedlcruz** [comment]
Thank you, should be okay now, just used the same query. Cheers!
