### ISSUE TITLE
Issue getting cluster names from vcenter

### ISSUE THREAD

**Issue by The-Funk** [jorgedlcruz/vmware-grafana#24]
Specs:
VCenter 6.7 U3
Telegraf 1.15.2
CentOS 8
Grafana 7.1.1
Influxdb Shell 1.8.1

The clusternames variable in the dashboard is not populating. I have two clusters and neither appear in the list. The vcenter server and esxi hosts populate correctly. The cluster CPU and mem usage are reporting incorrectly as well but I think this might be a product of the clusternames variable not populating correctly. Is there anything I can do to help troubleshoot this?

**Comment by The-Funk** [comment]
Is there a table in Influx that I could check if telegraf is pulling this information from vcenter, or a means that I could directly query the vcenter API using something like postman? I am wondering if this issue isn't caused by the telegraf plugin.

**Comment by jorgedlcruz** [comment]
Hello,
It is a known issue with the telegraf v1.15, I know the telegraf guys will release a new update this week, sorry for the trouble. Let's wait.

**Comment by jorgedlcruz** [comment]
Hello, this has been resolved in telegraf 1.15.3, take a look here https://www.jorgedelacruz.es/2020/09/15/telegraf-ya-disponible-telegraf-v1-15-3-solucionado-el-problema-que-no-monitorizaba-metricas-de-cluster-vmware/ and update, please.
