### ISSUE TITLE
Auto scaling time interval - Overview Dashboard

### ISSUE THREAD

**Issue by Scifire** [jorgedlcruz/vmware-grafana#28]
Hey,

first thanks for your work, these Dashboards are awesome!
Today I ran a bit in trouble cause I wanted to show the Overview Dashboard for around 30 days. This first overload my influxDB but the failed the query.

In my case the issue were the VM stats on the Board. They didn´t scale the requested data points. 
So for the "Virtual Machine CPU Usage in %" you query the mean usage_average and group them by 20 seconds.

For 30d  that´s not needed to have it in 20 seconds steps  so I´ve changed this to `$_interval` which will auto scale the "group by" requested time. 
I´ve changed this for most of the querys on the overview dashboard which result in much faster loading.

Is there a specific reason why you use group by `20sec` and not `$_interval` ? 

Example here:
https://github.com/jorgedlcruz/vmware-grafana/blob/master/VMware%20vSphere%20-%20Overview.json#L4819

**Comment by jorgedlcruz** [comment]
Hello, 
Thank you so much for the comment! And for the input, yes the 20 seconds mark is how VMware is giving you the metrics, if configured on telegraf, so selecting that would match VMware output, but I agree than on larger views, like 30 days, with dozens or hundreds of VMs might be too granular, let me explore the interval to see if it does matches VMware output and will change it.

:)

**Comment by Scifire** [comment]
Thanks for looking into it :) 

In my case I changed this value for metrics under "Virtual Maschine Status" and also the "Hypervisor Status". 
When I tried this at "Cluster Network Status" the values changed too much and seem not reflecting the truth anymore but this is already set on 5m so no need to change it. 

Just tested a bit around: I didn´t found any issue that it is showing wrong stats also while setting the shown time range to e.g. 15 min which will result in a group by 1 sec.

**Comment by jorgedlcruz** [comment]
Hello, changed all the Dashboards to use the sampling at the top, which is by default automatic, and works much better when expanding more in time, like weeks, or months.
Let me know, try the latest version of the dashboards, will close it for now.

**Comment by Scifire** [comment]
Hey,
thanks for the update, I like the new view :)
Unfortunately, in my case again I`m getting timeouts when I request a lager view e.g. 30 days. 
But this time it comes through a changed query I guess, cause the variables are timing out now.

The graph blocks itself are loading now much better but if I change the time range I have to fold and fold out the panels otherwise they won´t represent the selected time range.
