### ISSUE TITLE
CPU utilization is showing wrong in the grafana dashboard

### ISSUE THREAD

**Issue by Udayendu** [jorgedlcruz/vmware-grafana#30]
- CPU utilization is showing wrong on at the cluster level
  - Actual value in the Grafana dashboard:
    ![image](https://user-images.githubusercontent.com/1809177/115663215-cf4abd80-a35d-11eb-9402-039eab7b72c2.png)

  - actual value in the vCenter level
    ![image](https://user-images.githubusercontent.com/1809177/115663396-0c16b480-a35e-11eb-979a-02b8a069e602.png)

- Calculation:
  - Memory used:  (95.5/255.88)*100=37.27 % in GiB
  - CPU used:  (5.5/23.97)*100= 22.95 % in GHZ

As per the above calculation the above memory utilization is showing correct but not the CPU utilization. And its same for all the clusters that I have in my vCenter. Seems like instead of showing the utilization its showing the free amount for CPU.

- Similarly for another cluster, its continuously showing the CPU utilization s 100% but the actual utilization in vCenter is different.
  - Grafana utilization:
    ![image](https://user-images.githubusercontent.com/1809177/115668006-2c497200-a364-11eb-9478-f06e4e168cfe.png)

  - vCenter utilization:
    ![image](https://user-images.githubusercontent.com/1809177/115668107-4edb8b00-a364-11eb-96e3-e41000636d84.png)

**Comment by jorgedlcruz** [comment]
Hello, yes, should be fixed now, try with the latest revision and let me know - https://grafana.com/grafana/dashboards/8159/revisions

**Comment by Udayendu** [comment]
@jorgedlcruz 
Thanks for looking into this.

Now this value is looking good. Thanks for looking into this.
I will close this bug now.
