### ISSUE TITLE
Datastore" graphs are empty.

### ISSUE THREAD

**Issue by maneshmohanan1** [jorgedlcruz/vmware-grafana#32]
All data is available under the dashboard, However -Datastore graphs are empty.

**Comment by CrautDealer** [comment]
can confirm, having the same issue. Which vcenter version are you running? I'm currently on 7.0.2.
had it working before with vCenter version 6.

**Comment by jorgedlcruz** [comment]
Hello,
Are you using the latest version of the Dashboard available on Grafana? https://grafana.com/grafana/dashboards/8162 I am on 7.0 U3, but had it working in U2, U1, etc.

**Comment by maneshmohanan1** [comment]
Thanks for the replay, it working now  👍

**Comment by CrautDealer** [comment]
thanks for the reply, i just took another look into my grafana setup - it started working here too. :)

**Comment by jorgedlcruz** [comment]
Thanks guys!
