### ISSUE TITLE
Possible Wrong Filter

### ISSUE THREAD

**Issue by JohnFedorchak** [jorgedlcruz/vmware-grafana#6]
The "Network Usage" panel of the "VMware vSphere - VMs" dashboard has 2 queries. The one that's selecting bytesTx_average is grouping by tag(disk). 

I'm not sure if this is intentional or not, but it creates an "undefined bytesTx" in the legend.

**Comment by jorgedlcruz** [comment]
Good catch, fixed and uploaded to GitHub and Grafana - https://grafana.com/dashboards/8168/revisions
