### ISSUE TITLE
Incorrect values due to use of mean() on already averaged values

### ISSUE THREAD

**Issue by sawo1337** [jorgedlcruz/vmware-grafana#9]
I've noticed that the Overview dashboard showed incorrect IOPS when specific VM is selected. I've been executing a benchmark and I was closely monitoring the IOPS in the application and VMware earlier, but when I checked Grafana, the values were about twice as low compared to the actual values.
Looks like the mean() function which is used by default averages the values, however, the metric itself is averaged already (for example numberReadAveraged_average). When I selected last() instead, the correct values were shown for IOPS.
I guess this applies to several other metrics which are averaged in the data itself, using last() there would greatly improve the accuracy.

**Comment by jorgedlcruz** [comment]
Hello sawo, you are right, let me change the ones where it does make sense for better and more accurate results, I already did change some for RAM consumption like a week ago :)

Cheers!

**Comment by sawo1337** [comment]
Perfect, thanks! :)

**Comment by jorgedlcruz** [comment]
News Dashboards are now online, try them and close the issue if now are better :)

**Comment by sawo1337** [comment]
Thanks, looks good!
